build:
  commands:
    - echo "Files in repository"
    - ls -l

    - echo "Running Python Program"
    - python numbers.py

    - echo "Compiling Java Program"
    - javac Main.java

    - echo "Running Java Program"
    - java Main
