version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17

  build:
    commands:
      - echo "Current Directory"
      - pwd

      - echo "Files in Repository"
      - ls -R

      - echo "Python Version"
      - python --version

      - echo "Running Python Program"
      - python python/numbers.py

      - echo "Compiling Java"
      - javac java/Main.java

      - echo "Running Java"
      - java -cp java Main
